# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a3711eb4ab1d442d0a18f43977717fa66cb26e982ae34a1f733472cb21127794dc487218d15acb95d56d59b11e0962dfc3b093c3ff7e6055342a7ec9fdd8c07

test:
  secret_key_base: a186061995b2c3b260236f4068293f1fea6122a90df201dbc5482cda53e2a01a534445827410d28f6232d75492ade4913c43791a9fcd27c567d8a631e8457e2c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
