const
    mongoose = require ('mongoose'),// allows us to model application data
    dinosaurSchema = new mongoose.Schema({
        height: Number,
        species: String,
    }, { timestamps: true}) // this automatically generated by mongoose

    module.exports = mongoose.model('Dinosaur', dinosaurSchema)// allows us to retrieve the schema
    