const
mongoose = require ('mongoose'),// allows us to model application data
videoSchema = new mongoose.Schema({//this is how we set up the schema for video model
    title: {type: String, required: true},
    category: {type: String, default: "Uncategorized"},
    url: {type: String, required: true}
}, { timestamps: true}) // this automatically generated by mongoose which gives us a timestamp when things are created

module.exports = mongoose.model('Video', videoSchema)// allows us to retrieve the schema and name the model
